### ISSUE TITLE
Most HANGUL SYLLABLEs are missing medial vowels

### ISSUE THREAD

**Issue by duerst** [janlelis/unicode-name#1]
Most HANGUL SYLLABLEs are missing medial vowels. For example,
```Unicode::Name.of "\uAC1C"```
should produce `"HANGUL SYLLABLE GAE"`, but it only produces `"HANGUL SYLLABLE G"`. Similar for most other HANGUL SYLLABLEs. It looks like only the first medial vowel, "A", actually works.

This issue was discovered by my student Kohei Eda.

**Comment by janlelis** [comment]
Thank you for reporting this issue (and, btw, for all the work you do to have good Unicode support in Ruby).

It's now fixed in v1.13.1
